apiVersion: v1
kind: Pod
metadata:
  labels:
    test: ana-node-readiness
  name: ana-node-readiness-exec
spec:
  containers:
  - name: ana-node-readiness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

