apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ana-node
  labels:
    app: ana-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ana-node
  template:
    metadata:
      labels:
        app: ana-node
    spec:
      containers:
      - name: ana-node
        image: anastasiia_cloud_five:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /livetest
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livetest
            port: 5000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
